version: '3.5'

services:

  postgresql:
    image: 'postgres:16-alpine'
    container_name: postgresql
    ports:
      - "5433:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=userDb
    restart: always
    networks:
      - backend

#volumes:
#  postgres-data:
#    name: postgres-data

networks:
  backend: { }
